---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev-deployment
  namespace: webapp-dev
spec:
  selector:
    matchLabels:
      app: webapp-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: webapp-pvc
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "700m"
          limits:
            memory: "256Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
  namespace: webapp-dev
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
