---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev-deployment
  namespace: webapp-dev
spec:
  selector:
    matchLabels:
      app: webapp-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: webapp-pvc
      containers:
      - name: nginx
        image: nginx:1.29
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "700m"
          limits:
            memory: "256Mi"
        volumeMounts:
          - name: data-volume
            mountPath: /usr/share/nginx/html/speed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
  namespace: webapp-dev
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: webapp-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/webapp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8sworker01
          - k8sworker02
          - k8sworker03
