apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: webapp-dev
  name: webapp-vpa
  namespace: webapp-dev
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      maxAllowed:
        cpu: 1
        memory: 500Mi
      minAllowed:
        cpu: 10m
        memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-dev-deployment
  updatePolicy:
    updateMode: Auto
