apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway-http
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: web-gw-http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway-https
  namespace: kube-system
spec:
  gatewayClassName: cilium
  # addresses:
  #   - type: IPAddress
  #     value: 10.192.168.202
  listeners:
    - name: web-gw-https
      protocol: HTTPS
      port: 8043
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: cilium-gateway-https-secret
---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: bare-metal-pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 192.168.11.240/28
#
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: bare-metal-l2-advertisement
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - bare-metal-pool
