
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway-http
  namespace: kube-system
spec:
  gatewayClassName: cilium
  listeners:
    - name: web-gw-http
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway-https
  namespace: kube-system
spec:
  gatewayClassName: cilium
  # addresses:
  #   - type: IPAddress
  #     value: 10.192.168.202
  listeners:
    - name: web-gw-https
      protocol: HTTPS
      port: 8043
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: cilium-gateway-https-secret
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: bare-metal-pool
  # Spravidla sa deployuje do namespace, kde beží Cilium (často kube-system)
  namespace: kube-system
spec:
  # Definuj rozsah IP adries vo svojej lokálnej sieti, ktoré sú voľné!
  blocks:
  - cidr: "192.168.1.240/28" # Príklad: rozsah od 192.168.1.240 do 192.168.1.255
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: kube-system
spec:
  # Zoznam rozhraní (interface) na tvojich uzloch, cez ktoré má Cilium inzerovať IP.
  # Ak nevieš, nechaj prázdne (alebo použite regex: "eth.*" ak je to potrebné)
  interfaces:
    - ^enp$

  # Príklad: - ^eth0$
  # Príklad 2: Nechaj prázdne, ak má inzerovať na všetkých

  # Ak má inzerovať IP adresy, ktoré mu pridelil CiliumLoadBalancerIPPool
  loadBalancerIPs: true
  # Ak má inzerovať IP adresy ručne zadané v Service.spec.externalIPs
  externalIPs: true

  # Voliteľné: Ak chceš, aby táto politika platila len pre pool
  # loadBalancerIPPoolSelector:
  #   matchLabels:
  #     pool: bare-metal-pool



# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: bare-metal-pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 192.168.11.240/28
#
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: bare-metal-l2-advertisement
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - bare-metal-pool
