apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: gcp-secret-manager-store
    kind: ClusterSecretStore
  target:
    name: monitoring-grafana
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"                # fixed literal, not pulled from GCP
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminPassword             # local variable name, referenced in template above
      remoteRef:
        key: grafana-admin-password                # name of the secret in GCP Secret Manager
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
