apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: gcp-secret-manager-store
    kind: ClusterSecretStore
  target:
    name: monitoring-grafana
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"
        admin-password: '{{`{{ .adminPassword }}`}}'
  data:
    - secretKey: adminPassword
      remoteRef:
        key: grafana-admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
