##Example for the creation of a secret from the file '.secret' containing the alertmanager configuration, including smtp credentials

#kubectl create secret generic alertmanager-prometheus-kube-prometheus-alertmanager -n monitoring --from-file=alertmanager.yaml=.secret

## Example of .secret file
# global:
#   smtp_smarthost: 'smtp.gmail.com:587'
#   smtp_from: '<auth_username>@gmail.com'
#   resolve_timeout: 5m
# route:
#   group_by: ['alertname','job']
#   group_wait: 30s
#   group_interval: 5m
#   repeat_interval: 12h
#   receiver: 'smtp'
#   routes:
#   - match:
#       alertname: 'InfoInhibitor'
#     receiver: 'null'
# receivers:
# - name: 'null'
# - name: 'smtp'
#   email_configs:
#   - to: 'mygmail@gmail.com'
#     auth_username: '<auth_username>@gmail.com'
#     auth_password: 'secpassword'
#     require_tls: true
#     send_resolved: true

