apiVersion: v1
data:
  alertmanager.yaml.gz: H4sIAAAAAAAAA31QyU7DQAy95yvmNhKiCYsqUE78B0KRmzrJkNmwnSn8PTNpWpULN+v52W8ZbTiAbSul2Ens2AHJFFhapQtQjw6Mrfvg2v3ri77QBsqA0pPxKHUyJAvYtyu10Ag52ISdGIdhye/2rqI8YJEa8xS7w0+r3jVYJPHgUN/rz3DQH9f9CUy+e37gK2K8IKVst3wrGhFBbtDHp2mFezQJaYuwuinK3FaXVR53qojecLDY7/rgBzNycblTEvJ+IPBiGOeaZ4se6G9QpWCRqVsYaXv4TysbOQLzKdAxkyH5NJxmG77nzxhjOrMIvxZDuT3LrRJacEUZ/bHbij1uuKCLFtZwO6UblL5ZG3XgYURqznmau1oyT1e/kEzd+u8BAAA=
kind: Secret
metadata:
  labels:
    managed-by: prometheus-operator
  name: alertmanager-monitoring-kube-prometheus-alertmanager-generated
  namespace: monitoring
type: Opaque
