apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'webapp-dev'
spec:
  destination:
    name: ''
    namespace: ''
    server: ''
  source:
    path: ''
    repoURL: ''
    targetRevision: HEAD
  sources: []
  project: 'salaserver'

