apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'webapp-dev'
spec:
  destination:
    name: 'salaserver'
    namespace: 'webapp-dev'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/webapp/application.yaml'
    repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
    targetRevision: HEAD
  sources: []
  project: 'salaserver'

