
# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: Gateway
# metadata:
#   name: cilium-gateway-http
#   namespace: kube-system
# spec:
#   gatewayClassName: cilium
#   listeners:
#     - name: web-gw-http
#       protocol: HTTP
#       port: 8000
#       allowedRoutes:
#         namespaces:
#           from: All

# apiVersion: v1
# kind: List
# metadata:
#   resourceVersion: ""
# items:
# - apiVersion: gateway.networking.k8s.io/v1
#   kind: GatewayClass
#   metadata:
#     annotations:
#       argocd.argoproj.io/tracking-id: cilium:gateway.networking.k8s.io/GatewayClass:kube-system/cilium
#       meta.helm.sh/release-name: cilium
#       meta.helm.sh/release-namespace: kube-system
#     labels:
#       app.kubernetes.io/managed-by: Helm
#     name: cilium
#   spec:
#     controllerName: io.cilium/gateway-controller
#     description: The default Cilium GatewayClass

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway-https
  namespace: kube-system
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.0.202
  listeners:
    - name: web-gw-https
      protocol: HTTPS
      port: 8043
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: cilium-gateway-https-secret
    - name: headlamp-https
      protocol: HTTPS
      port: 8043
      hostname: headlamp.linuxadmin.eu
      tls:
        mode: Terminate
        certificateRefs:
        - name: headlamp-tls-secret
          kind: Secret
          namespace: headlamp
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: bare-metal-pool
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.0.0/24"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
  namespace: kube-system
spec:
  interfaces:
    - ^enp$
  loadBalancerIPs: true
  externalIPs: true


# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: bare-metal-pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 192.168.11.240/28
#
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: bare-metal-l2-advertisement
#   namespace: metallb-system
# spec:
#   ipAddressPools:
#   - bare-metal-pool
