apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-agent
  namespace: kube-system
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: prometheus
    interval: 5s
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-operator
  namespace: kube-system
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      name: cilium-operator
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: prometheus
    interval: 5s
    honorLabels: true



