apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'webapp-dev'
spec:
  destination:
    name: 'salaserver'
    namespace: 'webapp-dev'
    server: ''
  source:
    path: 'applications/webapp-dev/manifests'
    repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
    targetRevision: HEAD
  sources: []
  project: 'salaserver'
---
apiVersion: v1
kind: Namespace
metadata:
  name: webapp-dev
  labels:
    name: webapp-dev
