apiVersion: v2
name: gitlab
type: application
version: v19.2.0

dependencies:
  - name: gitlab
    version: 10.2.0
    repository: https://charts.gitlab.io/
  - name: garage
    version: 0.7.1
    repository: https://datahub-local.github.io/garage-helm
