gitlab:
  gitlab:
    toolbox:
      backups:
        objectStorage:
          config:
            secret: gitlab-object-storage-s3cmd
            key: config
  gitlab-runner:
    install: true
    rbac:
      create: true
    runners:
      locked: false
      # Set secret to an arbitrary value because the runner chart renders the gitlab-runner.secret template only if it is not empty.
      # The parent/GitLab chart overrides the template to render the actual secret name.
      secret: "nonempty"
      config: |
        [[runners]]
          name = "default-k8s"
          run_untagged = true
          request_concurrency = 2
          [runners.kubernetes]
            image = "ubuntu:24.04"

  prometheus:
    install: false

  postgresql:
    install: false

  redis:
    install: false


  # postgresql:
  #   persistence:
  #     volumeName: gitlab-postgres
  #     storageClass: local-storage
  # minio:
  #   install: false
  #   persistence:
  #     volumeName: pv-gitlab-minio
  #     storageClass: local-storage
  #     annotations:
  #       helm.sh/resource-policy: "keep"
  # redis:
  #   master:
  #     persistence:
  #       volumeName: gitlab-redis
  #       storageClass: local-storage
  # gitlab:
  #   gitaly:
  #     persistence:
  #       volumeName: gitlab-gitaly
  #       storageClass: local-storage

  # gitlab:
  #   migrations:
  #     enabled: true
  upgradeCheck:
    enabled: true
  installCertmanager: false
  certmanager:
    installCRDs: false
  certmanager-issuer:
    email: frantisek.sklenar@gmail.com
  nginx-ingress: &nginx-ingress
    enabled: false
  global:
    minio:
      enabled: false
  appConfig:
    object_store:
      enabled: true
      # If you aren't exposing Garage through the Ingress Gateway API, set object storage download proxying to true
      proxy_download: true
      connection:
        secret: gitlab-object-storage
        key: config
    # Set to buckets created in Garage. Can be omitted if you used the default bucket names.
    artifacts:
      bucket: gitlab-artifacts
    lfs:
      bucket: git-lfs
    uploads:
      bucket: gitlab-uploads
    packages:
      bucket: gitlab-packages
    externalDiffs:
      enabled: true
      bucket: gitlab-mr-diffs
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
    agentPlanContent:
      enabled: true
      bucket: gitlab-agent-plan-content
    dependencyProxy:
      enabled: true
      bucket: gitlab-dependency-proxy


    psql:
      host: gitlab-rails-db-rw.gitlab.svc.cluster.local
      password:
        secret: gitlab-rails-db-app
        key: password
    redis:
      auth:
        enabled: false
      host: redis-service.gitlab.svc.cluster.local
    ingress:
      enabled: false
    # ingress:
    #   apiVersion: "networking.k8s.io/v1"
    #   class: "nginx"
    hosts:
      domain: linuxadmin.eu
      externalIP: 192.168.0.202

#upgrade 19: https://docs.gitlab.com/charts/installation/migration/bundled_chart_migration/
#gitlab helm chart values: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml
#minio: https://github.com/minio/minio/tree/master/helm/minio
#rustfs: https://github.com/rustfs/rustfs/blob/main/helm/rustfs/values.yaml


