# garage:
#   # Data persistence
#   persistence:
#     enabled: true
#     meta:
#       storageClass: local-path
#       size: 200Mi
#     data:
#       storageClass: local-path
#       size: 500Mi

gitlab:
  gitlab:
    toolbox:
      backups:
        objectStorage:
          config:
            secret: gitlab-object-storage-s3cmd
            key: config
  gitlab-runner:
    install: true
    rbac:
      create: true
    runners:
      locked: false
      # Set secret to an arbitrary value because the runner chart renders the gitlab-runner.secret template only if it is not empty.
      # The parent/GitLab chart overrides the template to render the actual secret name.
      secret: "nonempty"
      config: |
        [[runners]]
          name = "default-k8s"
          run_untagged = true
          request_concurrency = 2
          [runners.kubernetes]
            image = "ubuntu:24.04"

  prometheus:
    install: false

  postgresql:
    install: false

  redis:
    install: false


  # postgresql:
  #   persistence:
  #     volumeName: gitlab-postgres
  #     storageClass: local-storage
  # minio:
  #   install: false
  #   persistence:
  #     volumeName: pv-gitlab-minio
  #     storageClass: local-storage
  #     annotations:
  #       helm.sh/resource-policy: "keep"
  # redis:
  #   master:
  #     persistence:
  #       volumeName: gitlab-redis
  #       storageClass: local-storage
  # gitlab:
  #   gitaly:
  #     persistence:
  #       volumeName: gitlab-gitaly
  #       storageClass: local-storage

  # gitlab:
  #   migrations:
  #     enabled: true
  upgradeCheck:
    enabled: true
  installCertmanager: false
  certmanager:
    installCRDs: false
  certmanager-issuer:
    email: frantisek.sklenar@gmail.com
  nginx-ingress: &nginx-ingress
    enabled: false
  global:
    minio:
      enabled: false
    appConfig:
      object_store:
        enabled: true
        # If you aren't exposing Garage through the Ingress Gateway API, set object storage download proxying to true
        proxy_download: true
        connection:
          secret: gitlab-object-storage
          key: config
      # Set to buckets created in Garage. Can be omitted if you used the default bucket names.
      artifacts:
        bucket: gitlab-artifacts
      lfs:
        bucket: git-lfs
      uploads:
        bucket: gitlab-uploads
      packages:
        bucket: gitlab-packages
      externalDiffs:
        enabled: true
        bucket: gitlab-mr-diffs
      terraformState:
        enabled: true
        bucket: gitlab-terraform-state
      ciSecureFiles:
        enabled: true
        bucket: gitlab-ci-secure-files
      agentPlanContent:
        enabled: true
        bucket: gitlab-agent-plan-content
      dependencyProxy:
        enabled: true
        bucket: gitlab-dependency-proxy

    psql:
      host: gitlab-rails-db-rw.gitlab.svc.cluster.local
      password:
        secret: gitlab-rails-db-app
        key: password
    redis:
      auth:
        enabled: false
      host: redis-service.gitlab.svc.cluster.local
    ingress:
      enabled: false
    # ingress:
    #   apiVersion: "networking.k8s.io/v1"
    #   class: "nginx"
    hosts:
      domain: linuxadmin.eu
      externalIP: 192.168.0.202

#upgrade 19: https://docs.gitlab.com/charts/installation/migration/bundled_chart_migration/
#gitlab helm chart values: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/values.yaml
#minio: https://github.com/minio/minio/tree/master/helm/minio
#rustfs: https://github.com/rustfs/rustfs/blob/main/helm/rustfs/values.yaml

###!!!!!IMPORTANT!!!!!
###Garage Installation:
# helm repo add garage-helm https://datahub-local.github.io/garage-helm
#
# helm install garage garage-helm/garage -n gitlab -f values.yaml
#
# kubectl exec garage-0 -n gitlab  -- /garage status
#
# kubectl exec garage-0 -n gitlab  -- /garage layout assign -z gitlab1 -c 500Mi <node1id>
# kubectl exec garage-1 -n gitlab  -- /garage layout assign -z gitlab2 -c 500Mi <node2id>
# kubectl exec garage-2 -n gitlab  -- /garage layout assign -z gitlab3 -c 500Mi <node3id>
#
# kubectl exec garage-0 -n gitlab -- /garage layout apply --version 1
#
#
# buckets=("git-lfs" "gitlab-agent-plan-content" "gitlab-artifacts" "gitlab-backups" \
#          "gitlab-ci-secure-files" "gitlab-dependency-proxy" "gitlab-mr-diffs" \
#          "gitlab-packages" "gitlab-pages" "gitlab-terraform-state" "gitlab-uploads" \
#          "registry" "runner-cache" "tmp" )
# for bucket in "${buckets[@]}"; do
#   kubectl exec -n gitlab garage-0  -- /garage bucket create "${bucket}";
# done
#
#
#
#
#
# local KEY_OUTPUT
# KEY_OUTPUT=$(kubectl exec -n gitlab garage-0 -- \
#     /garage key create gitlab-app-key)
#
# local GARAGE_ACCESS_KEY GARAGE_SECRET_KEY
# GARAGE_ACCESS_KEY=$(echo "${KEY_OUTPUT}" | grep 'Key ID:' | awk '{print $3}')
# GARAGE_SECRET_KEY=$(echo "${KEY_OUTPUT}" | grep 'Secret key:' | awk '{print $3}')
#
# # Grant permissions to the GitLab key.
# for bucket in "${buckets[@]}"; do
#   kubectl exec -n gitlab garage-0  -- /garage bucket allow --read --write --key gitlab-app-key "${bucket}";
# done
#
#
#
# cat <<EOF | kubectl create secret generic gitlab-object-storage -n gitlab --from-file=config=/dev/stdin
# provider: AWS
# region: garage
# aws_access_key_id: ${GARAGE_ACCESS_KEY}
# aws_secret_access_key: ${GARAGE_SECRET_KEY}
# endpoint: "http://garage.gitlab.svc.cluster.local:3900"
# path_style: true
# EOF
#
#
# cat <<EOF | kubectl create secret generic gitlab-object-storage-s3cmd -n gitlab --from-file=config=/dev/stdin
# [default]
# access_key = ${GARAGE_ACCESS_KEY}
# secret_key = ${GARAGE_SECRET_KEY}
# host_base = garage.gitlab.svc.cluster.local:3900
# host_bucket = garage.gitlab.svc.cluster.local:3900
# use_https = False
# EOF
#
#
# cat <<EOF | kubectl create secret generic gitlab-registry-storage -n gitlab --from-file=config=/dev/stdin
# s3:
#   accesskey: ${GARAGE_ACCESS_KEY}
#   secretkey: ${GARAGE_SECRET_KEY}
#   bucket: registry
#   region: garage
#   regionendpoint: http://garage.gitlab.svc.cluster.local:3900
#   secure: false
#   v4auth: true
#   pathstyle: true
# EOF
#


