# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: httproute-gitlab
#   namespace: immich
# spec:
#   hostnames:
#     - gitlab.linuxadmin.eu
#   parentRefs:
#     - group: gateway.networking.k8s.io
#       kind: Gateway
#       name: cilium-gateway-https
#       namespace: kube-system
#   rules:
#     - backendRefs:
#         - group: ''
#           kind: Service
#           name: gitlab-webservice-default
#           port: 8181
#           weight: 1
#       matches:
#         - path:
#             type: PathPrefix
#             value: /
#

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gitlab-gateway
  namespace: gitlab
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: gitlab.linuxadmin.eu
    tls:
      mode: Terminate
      certificateRefs:
      - name: gitlab-gitlab-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitlab-webservice-default
  namespace: gitlab
spec:
  parentRefs:
  - name: gitlab-gateway
    namespace: gitlab
  hostnames:
  - gitlab.linuxadmin.eu
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: gitlab-webservice-default
      port: 8181
