apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitlab-rails-db
  namespace: gitlab
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: gitlabhq_production
      owner: gitlab
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS btree_gist;
        - CREATE EXTENSION IF NOT EXISTS plpgsql;
        - CREATE EXTENSION IF NOT EXISTS amcheck;
        - CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-rails-db-1
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/gitlab/data-gitlab-postgresql-cn
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: gitlab-rails-db-1
    namespace: gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane

# kubectl exec -i -n gitlab $OLD_PG_POD -- env PGPASSWORD="$OLD_PG_PASSWORD" pg_dump -U postgres -Fc -b -v gitlabhq_production | \
# kubectl exec -i -n gitlab $NEW_CNPG_POD -- env PGPASSWORD="$NEW_CNPG_PASSWORD" pg_restore -U gitlab -d gitlabhq_production -h gitlab-rails-db-rw.gitlab --clean --if-exists -v

