---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-gitlab-postgresql-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/gitlab/data-gitlab-postgresql-0
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: data-gitlab-postgresql-0
    namespace: gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-minio
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/gitlab/gitlab-minio
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: gitlab-minio
    namespace: gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-data-gitlab-redis-master-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/gitlab/redis-data-gitlab-redis-master-0
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: redis-data-gitlab-redis-master-0
    namespace: gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-repo-data-gitlab-gitaly-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /srv/virtiofs/gitlab/repo-data-gitlab-gitaly-0
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  claimRef:
    name: repo-data-gitlab-gitaly-0
    namespace: gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - controlplane
