---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: postgresql
  name: data-gitlab-postgresql-0
  namespace: gitlab
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
#  volumeName: data-gitlab-postgresql-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
    app.kubernetes.io/managed-by: Helm
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
  name: gitlab-minio
  namespace: gitlab
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
#   # volumeName: gitlab-minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: gitlab
    app.kubernetes.io/name: redis
  name: redis-data-gitlab-redis-master-0
  namespace: gitlab
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  # volumeName: gitlab-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitaly
    release: gitlab
  name: repo-data-gitlab-gitaly-0
  namespace: gitlab
spec:
  storageClassName: "local-storage"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  # volumeName: gitlab-gitaly
