grafana-operator:
  ingress:
    enabled: true
    hosts:
      - grafana-operator-salaserver.linuxadmin.eu
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
