apiVersion: v2
name: kube-prometheus-stack

type: application

version: 75.9.0

dependencies:
- name: kube-prometheus-stack
  version: 75.9.0
  repository: https://prometheus-community.github.io/helm-charts
