cloudnative-pg:
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true
      namespace: monitoring
      labels:
        dashboards: "grafana"
        grafana_dashboard: "1"

