headlamp:
  httpRoute:
    enabled: true
    hostnames:
      - headlamp.linuxadmin.eu
      - headlamp.vpn.linuxadmin.eu
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: cilium-gateway-https
        namespace: kube-system
    rules:
      - backendRefs:
          - group: ''
            kind: Service
            name: headlamp
            port: 80
            weight: 1
        matches:
          - path:
              type: PathPrefix
              value: /
  image:
    tag: "v0.40.1"
  config:
    kubeConfigPath: ""
    clusterName: "local"
    args:
      - "-allow-all-namespaces"
    oidc:
      secret:
        create: false
  clusterRoleBinding:
    create: true
    clusterRoleName: headlamp-read-only
  serviceAccount:
    create: true
    name: "headlamp"
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  pluginsManager:
    enabled: true
    resources:
      requests:
        cpu: "100m"
        memory: "1024Mi"
      limits:
        memory: "4Gi"
