---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager-store
spec:
  provider:
    gcpsm:
      projectID: "449744778704"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-sa-key
            key: key.json
            namespace: external-secrets
