velero:
  credentials:
    useSecret: true
    name: k8s-sala-backup
    existingSecret: k8s-sala-backup
  configuration:
    backupStorageLocation:
    - name: aws-backup
      provider: aws
      bucket: k8s-sala-backup
      accessMode: ReadWrite
      credential:
        name: k8s-sala-backup
        key: cloud
      config:
        region: eu-central-1
    volumeSnapshotLocation:
    - name: aws-backup
      provider: aws
      credential:
        name: k8s-sala-backup
        key: cloud

