---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-application-controller
  namespace: argocd # Namespace where Argo CD is installed
  labels:
    release: kube-prometheus-stack # This label must match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  namespaceSelector:
    matchNames:
      - argocd # Namespace where Argo CD is installed
  endpoints:
  - port: metrics # This refers to the named port in the service, e.g., 'metrics' on argocd-metrics service
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server
  namespace: argocd # Namespace where Argo CD is installed
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
  - port: http # This refers to the named port in the service, e.g., 'http' on argocd-server service
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-repo-server
  namespace: argocd # Namespace where Argo CD is installed
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
  - port: http # This refers to the named port in the service, e.g., 'http' on argocd-repo-server service
    path: /metrics
    interval: 30s
