---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: argocd # Namespace where Argo CD is installed
  labels:
    release: monitoring # This label must match your Prometheus Operator's selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
      - argocd # Namespace where Argo CD is installed
  endpoints:
  - port: metrics # This refers to the named port in the service, e.g., 'metrics' on argocd-metrics service
    path: /metrics
    interval: 30s
