---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-tls
  namespace: headlamp # namespace where your app lives
spec:
  secretName: headlamp-tls-secret  # cert will be stored here
  issuerRef:
    name: letsencrypt-staging   # swap to letsencrypt-prod when ready
    kind: ClusterIssuer
  dnsNames:
  - headlamp.linuxadmin.eu
