apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      directories:
      - path: 'applications/*'
      repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
      revision: HEAD
      # files:
      # - path: applications/*/appset-values.yaml
      # repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
      # revision: HEAD
  syncPolicy:
    applicationsSync: create-only
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      ignoreDifferences:
      - group: batch # Kubernetes API group for Job
        kind: Job      # Kubernetes resource kind
        name: gitlab-issuer-e860305 # The specific name of the Job to ignore
      # ignoreDifferences:
      # - group: "" # Group is empty for core resources like Secret
      #   kind: Deployment
      #   jsonPointers:
      #   - /metadata/annotations/
      # - group: apiextensions.k8s.io
      #   kind: CustomResourceDefinition
      #   jsonPointers:
      #   - /spec/preserveUnknownFields
      project: "salaserver"
      sources:
      - repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
        #namespace: '{{.values.namespace}}'
        #namespace: '{{ .values.namespace | default path.basename }}'
      syncPolicy:
        syncOptions:
        - ServerSideApply=true
        - RespectIgnoreDifferences=true



