apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      directories:
      - path: 'applications/*'
      repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
      revision: HEAD
  syncPolicy:
    applicationsSync: create-only
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "salaserver"
      sources:
      - repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: kubernetes-dashboard-csrf
          namespace: kubernetes-dashboard
          jsonPointers:
            - /metadata/annotations
            - /data
      syncPolicy:
        syncOptions:
        - ServerSideApply=true


