
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationsethelm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      directories:
      - path: 'helm-charts/**/config.json'
      repoURL: 'https://github.com/fsklenar/argocd-salaserver.git'
      revision: HEAD
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "salaserver"
      sources:
      - repoURL: '{{.app.repo}}'
        chart: '{{.app.chart}}'
        targetRevision: '{{.app.revision}}'
        path: '{{.path.path}}'
        helm:
          valueFiles:
          - 'values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - '--helm-values'
          - 'values.yaml'

