apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager-store # A unique name for your ClusterSecretStore
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-manager-sa-key
            key: key.json # The key within the secret that holds the JSON content
