apiVersion: v2
name: immich
type: application
version: 2.7.5

dependencies:
- name: immich
  version: 0.13.1
  repository: oci://ghcr.io/immich-app/immich-charts
  #repository: https://immich-app.github.io/immich-charts

#helm chart values: https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
