# immich:
#   immich:
#     metrics:
#       enabled: true
#
#   redis:
#     enabled: true
#
#   server:
#     enabled: true
#     ingress:
#       main:
#         enabled: true
#         ingressClassName: nginx
#         annotations:
#           nginx.ingress.kubernetes.io/proxy-body-size: "0"
#         hosts:
#           - host: immich-salaserver.linuxadmin.eu
#             paths:
#               - path: "/"
#

env:
  REDIS_HOSTNAME: redis-service
  DB_HOSTNAME: "immich-postgres-service"
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  #DB_PASSWORD: ""

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-pvc



server:
  enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich-salaserver.linuxadmin.eu
          paths:
            - path: "/"
