immich:

  env:
    REDIS_HOSTNAME: redis-service
    TZ: "Europe/Bratislava"
    IMMICH_TELEMETRY_INCLUDE: all
    DB_HOSTNAME: "immich-postgres-service"
    DB_USERNAME: "immich"
    DB_DATABASE_NAME: "immich"
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: immich-postgres-secret
          key: db-password

  image:
    tag: v1.134.0

  immich:
    metrics:
      enabled: true
    persistence:
      library:
        existingClaim: virtiofs-psql-immich-claim #common storage for Immich and PostgreSQL (use different if you need to split them)

  server:
    enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: immich-salaserver.linuxadmin.eu
            paths:
              - path: "/"
