apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-secret
spec:
  refreshInterval: 8h # How often to check for updates in GCP Secret Manager
  secretStoreRef:
    name: gcp-secret-manager-store # Name of your ClusterSecretStore or SecretStore
    kind: ClusterSecretStore # Or 'SecretStore' if it's namespaced
  target:
    name: immich-postgres-secret # The name of the Kubernetes Secret to be created
    creationPolicy: Owner # Optional: ensure the secret is owned by the ExternalSecret
  data:
    - secretKey: db-password # The key name in the Kubernetes Secret
      remoteRef:
        key: immich-postgres-secret # The name of the secret in Google Cloud Secret Manager
