# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: immich-postgres-secret
#   namespace: immich # Ensure this matches your Immich namespace
# type: Opaque
# stringData:
#   POSTGRES_PASSWORD: changeme # <--- !!! CHANGE THIS TO A STRONG PASSWORD !!!
#   DB_PASSWORD: changeme # <--- !!! CHANGE THIS TO A STRONG PASSWORD !!!
#
