apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eck01
  namespace: elastic-system
spec:
  version: 9.3.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 2Gi
                cpu: 200m
              limits:
                memory: 4Gi

    # resources:
    #   requests:
    #     cpu: "200m"
    #     memory: "2Gi"
    #   limits:
    #     memory: "4Gi"
