apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: elastic-system
spec:
  version: 9.3.0
  count: 1
  elasticsearchRef:
    name: eck01
  http:
    tls:
      selfSignedCertificate:
        disabled: true
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-kibana
#   namespace: elastic-system
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: kibana-salaserver.linuxadmin.eu
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: eck-kibana-kb-http
#             port:
#               number: 5601
---
#https://github.com/cilium/cilium/issues/31352
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-kibana
  namespace: elastic-system
spec:
  hostnames:
    - kibana-salaserver.linuxadmin.eu
    - kibana-salaserver.vpn.linuxadmin.eu
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: cilium-gateway-https
      namespace: kube-system
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: eck-kibana-kb-http
          port: 5601
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /

