kyverno:
  cleanupController:
    rbac:
      create: true
      clusterRole:
        extraResources: []
  grafana:
    enabled: true
    grafanaDashboard:
      create: true
      folder: kyverno
      allowCrossNamespaceImport: true
      matchLabels:
        dashboards: "grafana"
  admissionController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring # Replace with your prometheus-stack release name
  backgroundController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  cleanupController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  reportsController:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  metricsConfig:
    enabled: true
        # - apiGroups:
        #     - ''
        #   resources:
        #     - pods
        #   verbs:
        #     - delete
        #     - list
        #     - watch
