kyverno:
  cleanupController:
    rbac:
      create: true
      clusterRole:
        extraResources: []
        # - apiGroups:
        #     - ''
        #   resources:
        #     - pods
        #   verbs:
        #     - delete
        #     - list
        #     - watch
