kyverno:
  cleanupController:
    rbac:
      create: true
      clusterRole:
        extraResources: []
  grafana:
    enabled: true
    grafanaDashboard:
      create: true
      folder: kyverno
      allowCrossNamespaceImport: true
      matchLabels:
        dashboards: "grafana"
  admissionController:
    metricsService:
      create: true
  backgroundController:
    metricsService:
      create: true
  cleanupController:
    metricsService:
      create: true
  reportsController:
    metricsService:
      create: true
        # - apiGroups:
        #     - ''
        #   resources:
        #     - pods
        #   verbs:
        #     - delete
        #     - list
        #     - watch
